language: ruby

install: gem install sass

script: make clean && make

after_success:
- export COMMITMESSAGE="$(git log -1 --pretty=%s)"
- echo "${COMMITMESSAGE}"
- mv ./*.html ..
- mv ./css/ ..
- mv ./scss/ ..
- mv ./js/ ..
- mv ./fonts/ ..
- mv .travis/deploy_key.enc ..
- git fetch origin gh-pages:gh-pages
- git checkout gh-pages
- git submodule init
- git submodule update
- rm -rf ./css/ ./scss/faufablab/ ./scss/*.scss ./js/ ./fonts/bootstrap/
- mv -f ../*.html .
- mv -f ../css/ .
- mv -f ../scss/faufablab ../scss/*.scss ./scss/
- mv -f ../js/ .
- mv -f ../fonts/bootstrap ./fonts/
- git add --all ./*.html ./css/ ./scss/ ./js/ fonts/
- git status
- git config --global user.name "Travis Auto Build"
- git config --global user.email "travis@fablab.fau.de"
- git commit -m "${COMMITMESSAGE}"
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_45b5f1ef936e_key -iv $encrypted_45b5f1ef936e_iv
  -in ../deploy_key.enc -out ../deploy_key -d
- chmod 600 ../deploy_key
- ssh-add ../deploy_key
- git remote add deploy git@github.com:fau-fablab/website-style.git
- git push deploy gh-pages
