language: ruby

install: gem install sass

script: make clean && make

after_success:
- export COMMITMESSAGE="$(git log -1 --pretty=%s)"
- echo "${COMMITMESSAGE}"
- cp ./index.html ..
- cp -r ./css/ ..
- cp -r ./js/ ..
- cp .travis/deploy_key.enc ..
- git checkout gh-pages
- mv ../index.html ./index.html
  mv ../css/ .
  mv ../js/ .
- git add ./index.html ./css/ ./js/
- git config --global user.name "Travis Auto Build"
- git config --global user.email "travis@fablab.fau.de"
- git commit -m "${COMMITMESSAGE}"
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_45b5f1ef936e_key -iv $encrypted_45b5f1ef936e_iv
  -in ../deploy_key.enc -out ../deploy_key -d
- chmod 600 ../deploy_key
- ssh-add ../deploy_key
- git remote add deploy git@github.com:fau-fablab/website-style.git
- git push deploy gh-pages
